language: php
php:
    - 7.2
    - 7.3
    - '7.4snapshot'
    - nightly
before_script: composer install
script: phpunit --coverage-clover=coverage.clover
after_script:
    - if [ -f coverage.clover ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
    - if [ -f coverage.clover ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
